services:
  - type: web
    name: enigma-crm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: enigma-crm-frontend
    env: static
    staticPublishPath: frontend 